server:
    port: 8888
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
        min-response-size: 1024
    session:
        timeout: 1800
spring:
   profiles.active: dev
   freemarker.cache: false
   resources.cache-period: 0
   datasource:
         url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false
         username: root
         password: root
         hikari:
             minimumIdle: 5
             maximumPoolSize: 15
             data-source-properties:
                 cachePrepStmts: true
                 prepStmtCacheSize: 250
                 prepStmtCacheSqlLimit: 2048
                 useServerPrepStmts: true
#  jpa配置
   jpa:
      show-sql: true
      hibernate:
          # Hibernate DDL  auto: create, create-drop, update, validate
          ddl-auto: validate
      properties:
          hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
          hibernate.current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext

#  i18n资源文件配置
   messages:
      basename: i18n/base/messages,i18n/ubi/messages,i18n/ubi/sys/messages,i18n/ubi/car/messages
      cache-seconds: -1
      encoding: UTF-8

#  redis单例配置
#   redis:
#      hostName: 10.10.35.99
#      port: 6379
#      timeout: 0
#      pool:
#          max-idle: 8
#          min-idle: 0
#          max-active: 8
#          max-wait: -1

#  redis分布式配置
#   redis:
#      cluster:
#          nodes:
#            - 10.10.35.99:6379
#            - 10.10.35.100:6379
#          connectionTimeout: 2000
#          soTimeout: 2000
#          maxAttempts: -1
#          maxIdle: 8
#          minIdle: 0
#          maxTotal: 8

#  redis集群配置
#   redis:
#      distributed:
#          nodes[0]:
#              host: 10.10.35.99
#              port: 6379
#              connectionTimeout:
#          nodes[1]:
#              host: 10.10.35.100
#              port: 6379
#              connectionTimeout:
#          maxAttempts: -1
#          maxIdle: 8
#          minIdle: 0
#          maxTotal: 8

#   rabbitmq配置
#   rabbitmq:
#      host: 121.40.157.200
#      port: 5672
#      username: briair
#      password: briair

#   kafka配置
#   kafka:
#      bootstrap-servers: 10.10.11.147:9092,10.10.11.148:9092,10.10.11.149:9092
#      consumer.group-id: zd
#      consumer.key-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
#      consumer.value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
#      producer.key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
#      producer.value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer